[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Code for Machine Learning Zoomcamp"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]
